### ISSUE TITLE
課題２　登録データ再利用登録

### ISSUE THREAD

**Issue by masayuki14** [takuo-maeda/calculate_calorie_app#10]
2　外食・中食登録データ再利用登録
課題２　登録データ再利用登録
現在外食・中食でcooked_foodへのデータベース登録が可能で、検索機能も実装しております。
今後ですが、検索結果を右横に編集ボタンを付けて登録されたデータを更新して新たな日付の食事データを登録の機能を実装したいと考えております。 
１　検索画面でメニューを検索 （実装済み）
２　検索した項目　右横に編集ボタンをつける 
３　編集ボタンを押すと登録画面にデータを入れた再登録画面として利用して再入力し
 ４　摂取日を最新の日程時間に変更して新規登録

**Comment by takuo-maeda** [comment]
2　外食・中食登録データ再利用登録
課題２　登録データ再利用登録
現在外食・中食でcooked_foodへのデータベース登録が可能で、検索機能も実装しております。
今後ですが、検索結果を右横に編集ボタンを付けて登録されたデータを更新して新たな日付の食事データを登録の機能を実装したいと考えております。 
１　検索画面でメニューを検索 （実装済み）
２　検索した項目　右横に編集ボタンをつける 
３　編集ボタンを押すと登録画面にデータを入れた再登録画面として利用して再入力し
 ４　摂取日を最新の日程時間に変更して新規登録
